export const SUCCESSFULL_LOGIN = "SUCCESSFULL_LOGIN";
export const SUCCESSFULL_LOGOUT = "SUCCESSFULL_LOGOUT";
export const RECEIPT_DATA_MODIFIED = "RECEIPT_DATA_MODIFIED";
export const RECEIPT_DATA_NOT_MODIFIED = "RECEIPT_DATA_NOT_MODIFIED";