export const SUCCESSFULL_LOGIN = "SUCCESSFULL_LOGIN";
export const SUCCESSFULL_LOGOUT = "SUCCESSFULL_LOGOUT";
export const RECEIPT_ADDED = "RECEIPT_ADDED";
export const RECEIPT_NOT_ADDED = "RECEIPT_NOT_ADDED";