//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.ReceiptItems = new HashSet<ReceiptItem>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int StoreId { get; set; }
        public string originalReceiptId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal TotalSum { get; set; }
        public Nullable<int> StoreTagId { get; set; }
        public System.DateTime creationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptItem> ReceiptItems { get; set; }
        public virtual User User { get; set; }
        public virtual Store Store { get; set; }
        public virtual StoreTag StoreTag { get; set; }
    }
}
